In [3]:
#Exercise A


import numpy as np


nested_list_A = [[i for i in range(1, 101)]]
A = np.array(nested_list_A)
print ("A. \n4 ",A) #This displays the list of values from 1 to 100 in a nested Python List

print("\n1. Shape of A:", A.shape) #The .shape gives the shape of the array A, which represents the number of rows and columns in the array.
print("\n2. Maximum value in A:", A.max())  # The .max gives the maximum value  in the array A.
print("\n3. Maximum value in A:", np.max(A))  #The np.max() function calculates the maximum value present in the array A assing an ndarray



A. 
4  [[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
   55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
   73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
   91  92  93  94  95  96  97  98  99 100]]

1. Shape of A: (1, 100)

2. Maximum value in A: 100

3. Maximum value in A: 100


In [4]:
#Exercise B
import numpy as np

ones = np.ones((5, 5), dtype=np.int32)  #This creates a 5x5 integer-array filled with ones.The dtype=np.int32 makes the array contains integer values.
print("B.\n", ones) #This displays the 5x5 integer filled with ones

print("Shape of ones_array:", ones.shape) #  The .shape: Returns the shape of the array
print("Size of ones_array:", ones.size) #  The .size: Returns the total number of elements in the array
print("Number of dimensions of ones_array:", ones.ndim) #  The .ndim: Returns the number of dimensions of the array




B.
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape of ones_array: (5, 5)
Size of ones_array: 25
Number of dimensions of ones_array: 2


In [14]:
#Exercise C
import numpy as np

original_array = np.arange(-5, 6) # Creating an array of values from -5 to +5
print("C.\nOriginal array: ",original_array) #Displayig the original array

result_array = original_array * 2 # Multiply each value by 2
print("Multiplied array: ", result_array) # Displaying the resulting of multiplied value


C.
Original array:  [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Multiplied array:  [-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [20]:
#Exercise A
import numpy as np

array = np.arange(1, 61, 2) #This creates an array with 30 values within the range of numbers from 1 to 100, with an increment of 2
print("\n1.\n",array) #This prints the 30 values

result = array * 3 # Multiplying result by 3

print("\n2.\n Resulting array after multiplying each value by 3:", result_array)



1.
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59]

2.
 Resulting array after multiplying each value by 3: [  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177]


In [23]:
# Exercise A
import numpy as np

# Create a 4D array of random integers in the range [0, 12]
array = np.random.randint(0, 13, size=(3, 4, 5, 6))
print("A.\nRandom Array:\n", array)

# Get the dimensions, shape, and size
dimensions = array.ndim
shape = array.shape
size = array.size
print("\nDimensions:", dimensions)
print("Shape:", shape)
print("Size:", size)




A.
Random Array:
 [[[[ 9  0  3  4  2 12]
   [12  6  3  2  4  4]
   [11  2  5  8 12  7]
   [ 2  8  0  9  4 11]
   [12  0  6  9  8  1]]

  [[ 9 12  5  2  6  1]
   [ 2  5 12  9  2  3]
   [12  3  5  0 10  4]
   [10 11  4  6  3  0]
   [ 1  4  7  0  3 10]]

  [[ 7  6  5  9 10  1]
   [ 2  3 11 10  6  0]
   [ 4 12 10 12  0  4]
   [ 2  7  0 12  8 11]
   [ 0  5  2  2  7 11]]

  [[ 6  7  1  6 12  9]
   [ 7  8 10 12  5 12]
   [11  9  3  5  9  6]
   [11  9  7  3  3  1]
   [ 2 10  2 12 10  3]]]


 [[[ 5  5  7  9  2  2]
   [12  4  1 11  7  3]
   [ 5 10 12  9 10  7]
   [ 2  6  6  2  5  5]
   [ 4 11  4 12 12 10]]

  [[10  3  8  5  7 10]
   [ 7  8  2  9  8 10]
   [ 6  3  6  8 12  3]
   [11  6 11  4  0  1]
   [ 1  1 10 10 12  4]]

  [[11  3  7 12  0  1]
   [10 10  0  0  5  2]
   [ 3  1 12  3  4  2]
   [ 0  8  5  5  9  4]
   [ 9  7  0 10 12 11]]

  [[ 1  6  2 10  1 10]
   [ 2  7  3 10  0 11]
   [ 9  4  1  9  5  5]
   [ 8  9  7  4  9 10]
   [ 2  8  1  9  0  2]]]


 [[[ 4  8  9  0  0 10]
   [ 9  5  6  3  7 

In [28]:
#Exercise B
import numpy as np


array = np.random.randint(0, 13, size=(3, 4, 5, 6))
max_per_dimension = np.max(array, axis=(0, 1, 2, 3))  #Calculating the maximum number
print("\nB. Maximum number for each dimension:", max_per_dimension)





B. Maximum number for each dimension: 12


In [31]:
#Exercise C
import numpy as np

array = np.random.randint(0, 13, size=(3, 4, 5, 6))

multiplied_array = array * 4 #Multiply each array with 4.

print("C. \nMultiplied array:\n", multiplied_array) # Print the multiplied array


C. 
Multiplied array:
 [[[[16 24  0 16 40 36]
   [40 32 40 20  8 40]
   [48 48 40  8 36  8]
   [36  4 16 24  0 12]
   [20 36 24 44  8  0]]

  [[36 16 12  4 24 44]
   [ 8 44 12 24  0 20]
   [16  4 24 16 12 12]
   [20 36  8 36 16 36]
   [48 44 44 20 32 16]]

  [[ 4 40 28 36 44 36]
   [ 0  0 40 32 44 44]
   [40 16 28  0 40 44]
   [ 0 12  8 24 36 40]
   [20  8 48 28 32  0]]

  [[20 24 32 48  0 32]
   [20 36 32 44 20 24]
   [24  8 40  0  8 28]
   [ 8 24 28 32  8 28]
   [20 40 48  8 16 20]]]


 [[[24 16 16  4  0 48]
   [16  8 36  4 32 44]
   [44 48 20 40 20 36]
   [48 20  0  4 48  8]
   [16  0 44 48 32 44]]

  [[40 40 48 24  8 48]
   [24 32 44 16  0 44]
   [ 0 16 40 44 48  0]
   [48  0 44 40 16  4]
   [40 12 36  4 32 48]]

  [[ 0 32  8  8  4 40]
   [12  8 28  4  0  0]
   [44 44 20 44 20 12]
   [ 8 32  8 16 12 48]
   [40 16 28 32 16 40]]

  [[36 28  4 40 40 36]
   [24 20 44 48 12 40]
   [28 20 48 48  0 16]
   [12 16  8  8 28 44]
   [20 48 28  4 44 12]]]


 [[[ 4 36 44 36 20 32]
   [48 24 20 2